<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thomas</name>
   <tag></tag>
   <elementGuidId>bc3720dc-86ac-4b48-bc8f-0279457d9ad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.qbl-username-link.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='right-leftitem']/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a0f81d3-9570-49a4-9c9c-e834c01b33be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbl-username-link ng-binding</value>
      <webElementGuid>f9b053ee-520f-4dfe-8638-adc8a8330235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thomas</value>
      <webElementGuid>af5c92a5-3191-4d81-accc-f275fdf506b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;right-leftitem&quot;)/div[@class=&quot;qbl-username&quot;]/a[@class=&quot;qbl-username-link ng-binding&quot;]</value>
      <webElementGuid>2d39cd20-fb61-4cde-93d7-a8c24be7dad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='right-leftitem']/div[4]/a</value>
      <webElementGuid>7d35933a-8d15-4415-b7b7-f38f01722f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Thomas')]</value>
      <webElementGuid>ec332e2f-c86c-4cef-9503-75dcd7ff4251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUR TRUSTED FAMILY BANK'])[1]/following::a[3]</value>
      <webElementGuid>2508d43f-9eaf-4b0b-a05f-cbf76f3254ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::a[1]</value>
      <webElementGuid>aae4ff25-30b7-48c6-ae1c-faaf93448615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::a[1]</value>
      <webElementGuid>1eaeaa7d-21ad-4e4c-a847-2e118d6e8aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thomas']/parent::*</value>
      <webElementGuid>14f881a2-7a56-4c2b-8887-10873faeef4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[3]</value>
      <webElementGuid>0bac94f5-44ca-46b2-b11e-fbd189e2b253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>e7285daa-5c71-4ae5-b039-52728482697a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Thomas' or . = 'Thomas')]</value>
      <webElementGuid>375aedb9-4769-4573-b445-651aca865f31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
