<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verify</name>
   <tag></tag>
   <elementGuidId>2eff9555-82fd-473c-86d9-a5c745d39998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sub-qb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sub-qb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5fe12f3-8755-4167-ba79-7ecde45cc2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub-qb</value>
      <webElementGuid>880d2457-8501-4910-ac0f-318b14a87d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>15f8f2c9-51d5-47f2-91a6-7d84359679e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>userCtrl.createNewCC()</value>
      <webElementGuid>94111b80-235c-49fd-83ca-8f5997dab524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-submit-button</value>
      <webElementGuid>be36adea-de39-4628-8736-9be88db07826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>f9a146fb-6db2-4f71-a09f-7feb9a638b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-qb&quot;)</value>
      <webElementGuid>c67c2646-aac6-4835-ad44-5664596a56ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sub-qb']</value>
      <webElementGuid>770ec376-01c1-4ef0-9c2a-64960010c220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newAcc-btn-sec']/button[2]</value>
      <webElementGuid>0caae6b0-dbc0-4f22-a1bc-d0a2944c46dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>51f999ec-4a8c-4840-a691-b8a1a86d9df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUR TRUSTED FAMILY BANK'])[2]/preceding::button[1]</value>
      <webElementGuid>a1f5bee0-cf64-45a5-9357-de4e7a3e59dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>751f4d11-d5d8-42c8-927f-2f3c4ad072a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sub-qb' and @type = 'submit' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>54503fb1-01aa-423f-9865-ea54d9a38201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
