<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Branches</name>
   <tag></tag>
   <elementGuidId>f876d094-7a73-4fd0-a517-ba35081900d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qb-nav-margin']/div[3]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>33af1fa7-1e42-484e-aaf0-ca1dad704a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-navbar-menuitem</value>
      <webElementGuid>f233580d-8334-481f-a904-0e65d9950c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>mainCtrl.goToState('BranchesPage')</value>
      <webElementGuid>26ac418d-ff93-43a0-b1ca-04d1484598c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>mainCtrl.isActiveState('BranchesPage') ? 'active' : ''</value>
      <webElementGuid>df4a15c0-dc50-4896-b1cb-e34c49b4fbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Branches
                    </value>
      <webElementGuid>a9405897-bb3f-4ce0-8013-efbf89d14acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qb-nav-margin&quot;)/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;qb-navbar-menu&quot;]/div[@class=&quot;qb-navbar-menuitem&quot;]</value>
      <webElementGuid>a0b1f24c-00a5-4a1a-8f8d-c4c31abea6e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-nav-margin']/div[3]/div/div[3]</value>
      <webElementGuid>2ae9c834-ba4e-4e0b-897e-16eadb57ac79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invest'])[1]/following::div[1]</value>
      <webElementGuid>5790d8bd-0970-4a50-bb6a-05578313b5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mortgage'])[1]/following::div[2]</value>
      <webElementGuid>23e30e40-4ff7-4dae-8ae9-1031c258c62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learning center'])[1]/preceding::div[1]</value>
      <webElementGuid>0af70cfd-a127-42ce-af0e-4783b6c849df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test App'])[1]/preceding::div[2]</value>
      <webElementGuid>eb01dc4e-d40f-4ffa-96ca-dad4f38da615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Branches']/parent::*</value>
      <webElementGuid>da894b66-b36b-4ac3-8739-49d62e5e34d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div[3]</value>
      <webElementGuid>f3d1efe8-919c-4548-b738-6833f29eae21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                        Branches
                    ' or . = '
                        Branches
                    ')]</value>
      <webElementGuid>444d43ac-6b70-497e-afed-6702ed64da04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
