<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Home</name>
   <tag></tag>
   <elementGuidId>d719503b-e8c1-42cb-bc4d-ec20dc912505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.qb-navbar-menuitem.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qb-nav-margin']/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b89cbb47-6a3f-4342-b5b4-6c8569c81759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-navbar-menuitem active</value>
      <webElementGuid>90c52320-8698-4515-8e2d-2a2167888dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>mainCtrl.goToState('HomePage')</value>
      <webElementGuid>9dbd6dcc-eae5-4154-b9aa-f92fd24d0378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>mainCtrl.isActiveState('HomePage') ? 'active' : ''</value>
      <webElementGuid>4e602691-eb77-4aea-9757-536a11d3ffcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Home
                    </value>
      <webElementGuid>b6e4545e-eb98-4215-8f95-957a74261bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qb-nav-margin&quot;)/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;qb-navbar-menu&quot;]/div[@class=&quot;qb-navbar-menuitem active&quot;]</value>
      <webElementGuid>4da1a466-6b0f-47d7-aadd-fb29cd2053af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-nav-margin']/div[3]/div/div</value>
      <webElementGuid>16f2bcc0-3c81-46e1-8f35-c7de0eaa5fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUR TRUSTED FAMILY BANK'])[1]/following::div[3]</value>
      <webElementGuid>537f6d05-f1c5-424d-a137-2ba9ffb40685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Card'])[1]/preceding::div[2]</value>
      <webElementGuid>54ccd938-1a14-46be-a3d7-26b6bee961ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>f495add7-7fca-420a-bab6-0e07448f58eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div</value>
      <webElementGuid>c0241101-48d7-4991-a154-23261dc093cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                        Home
                    ' or . = '
                        Home
                    ')]</value>
      <webElementGuid>293d8ff2-3e82-43d2-a691-8477cae7a944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
