<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount ()_qbf-amount-input</name>
   <tag></tag>
   <elementGuidId>779b0e1e-266d-4139-9aab-bac9e021df27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qbf-amount-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qbf-amount-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8ef3464-9516-455b-a67c-f8351029956c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qbf-amount-input</value>
      <webElementGuid>3d955a7e-4d0f-4d17-98a1-90f730ac7c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-input small ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>f3b85de7-9a98-4c58-abdd-166a7b049044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57d9d7e5-7978-4df9-a81f-cc18a8fc61ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>userCtrl.newTransaction.amount</value>
      <webElementGuid>c472689c-8c22-4f56-9684-bd57f5a9303b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>userCtrl.purposeOfAmount()</value>
      <webElementGuid>036d4d1d-f9c0-4d2e-a476-2739ff0f5818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qbf-amount-input&quot;)</value>
      <webElementGuid>3507f36f-6a15-4123-a694-e4a90beaa41a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qbf-amount-input']</value>
      <webElementGuid>0d802766-56df-4cf3-a87f-fe37036ffa55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-bil-input']/input</value>
      <webElementGuid>27c644ad-7aa3-46ce-9779-559930ba472d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>65082658-c20b-48a0-8ae5-0a48efcdc1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'qbf-amount-input' and @type = 'text']</value>
      <webElementGuid>40dd0f9c-34e1-4171-af79-bccdbdeb041b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
