<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Corporate Banking_qb-username</name>
   <tag></tag>
   <elementGuidId>5030c6b2-425b-4963-b29e-72cf5be5d101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qb-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qb-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0dc7965-99cd-4538-acbc-3fc11d763e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f6f3716-872a-41fa-9dd4-aaa323af51a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qb-username</value>
      <webElementGuid>282e1919-3865-448a-a479-6ad7d0f7b23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>ceaea118-013e-4064-aafa-3e885fd40fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>43640fa0-2762-4c87-9edb-79e7f66fc355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-signin-input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>64df5259-0814-4d63-b598-5e37315aae4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qb-username&quot;)</value>
      <webElementGuid>0ed02d8f-dfdb-45a2-a84e-beacca61ddd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qb-username']</value>
      <webElementGuid>1063c942-50d4-49ad-ab5f-fc459891751e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-login-container']/div/div[2]/div/div[2]/div/form/div[3]/input[2]</value>
      <webElementGuid>89b5319a-e84b-4ea2-8633-342d762bdc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[2]</value>
      <webElementGuid>fadce6a3-4d6b-45df-a93a-50cc96e6079b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'qb-username' and @placeholder = 'Username']</value>
      <webElementGuid>8c44e7c2-77ba-4f0b-802b-50b57f3c0729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
