<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Memo_qbf-memo-input</name>
   <tag></tag>
   <elementGuidId>a0e05354-b2f7-449f-812a-73aa78e1633e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qbf-memo-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qbf-memo-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa3bf295-d4e8-4e05-9521-164174f18b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qbf-memo-input</value>
      <webElementGuid>01ff55ab-c043-40ad-8820-a57f0f99ded1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-input small ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>f107b3cd-d222-45c3-9563-98212d15cab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>userCtrl.newTransaction.description</value>
      <webElementGuid>e8c04982-d270-44e1-bba4-8ce3feafa4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc9b9008-9b69-4ce2-ab60-f2b835ab990a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qbf-memo-input&quot;)</value>
      <webElementGuid>06d6d8e3-fdab-412c-8cf8-4685401452e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qbf-memo-input']</value>
      <webElementGuid>97b6a268-6344-4c5c-b88d-52aff5d49549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='qb-bil-input']/input)[3]</value>
      <webElementGuid>f4cdb0ec-93d9-4650-b2a8-275b23febd1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>ef2b6883-11d7-4098-a18d-2aafab3aacc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'qbf-memo-input' and @type = 'text']</value>
      <webElementGuid>54d71e89-639d-4359-9ca0-17d044944a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
