<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Corporate Banking_Password</name>
   <tag></tag>
   <elementGuidId>e2a270b4-1d80-47c7-bacd-f80b906cd0da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qb-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qb-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90103a3e-eb17-46c7-b2b3-ccc82175f6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e59fcd5f-cd80-4a91-b635-abb7072d9402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qb-password</value>
      <webElementGuid>6ff02207-e6c6-48f0-9e48-5d532508c0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>e5acd41b-d919-446a-9f5e-974429027e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>04a96717-68df-4231-90a1-6732e1508859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0bc855ca-6f13-4796-8c38-04656ac2e5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-signin-input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>7df174e3-4a9f-49ac-98f8-af50d4894d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qb-password&quot;)</value>
      <webElementGuid>104d1814-318e-4850-adab-292bca97187f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qb-password']</value>
      <webElementGuid>f860a5d1-b6f5-429f-be29-f9533cf10396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-login-container']/div/div[2]/div/div[2]/div/form/div[3]/input[3]</value>
      <webElementGuid>352c815f-9d4f-4677-85df-145fde5d01dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>1425d7c0-e828-4bfe-ae27-5cd9d901e800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'qb-password' and @name = 'Password' and @placeholder = 'Password']</value>
      <webElementGuid>0a753ea9-2e55-47bb-a93d-2188adf6d275</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
