<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Find a QBank Branch or ATM near you_b_3291a6</name>
   <tag></tag>
   <elementGuidId>245c40c4-1a1e-48f7-a949-ba82f1409262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#branch-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='branch-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3389769a-7615-4b05-ba24-7cd94ccabcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch-input</value>
      <webElementGuid>58a2cf26-3c90-4a2d-8a49-d2935bcc93a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f384c732-9d2c-4a94-9ac0-e9f443571f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dallas, Texas</value>
      <webElementGuid>5e10b85d-e25d-4749-a68c-d86bb0d31df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>branchSearchStr</value>
      <webElementGuid>7e957857-5309-4f28-bb2d-824c11fcffe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>6921a69a-94a9-4df6-8f35-18b30c616bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch-input&quot;)</value>
      <webElementGuid>f4354f07-39e7-4b6c-bece-d45043e91b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='branch-input']</value>
      <webElementGuid>bb1f3e10-2585-45c7-8ad9-4c7b2cf770ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/div/div/div[2]/div[2]/form/input</value>
      <webElementGuid>03d1354b-d3c3-4c46-baf4-c00456ef490b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>120906dc-15d8-4c43-8c81-534bdf261f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'branch-input' and @type = 'text' and @placeholder = 'Dallas, Texas']</value>
      <webElementGuid>698accbd-757f-4db3-b9d3-bd3435cf22f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
