<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input6</name>
   <tag></tag>
   <elementGuidId>749576fc-c941-4b9b-8d90-8e05390be001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32635f32-65e9-4965-9c60-3074afc4e84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-input xs ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>39742a44-de24-4fa6-9c70-61681f35c859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b367d8ed-76f6-48ee-896b-00258895cf91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>userCtrl.newCC.year</value>
      <webElementGuid>ae5e1f70-b2d1-4f54-8234-214992a2c797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YY</value>
      <webElementGuid>2f56593c-a389-4fc4-a654-e53453256b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input6</value>
      <webElementGuid>e08dbb20-572e-4272-a5eb-8a6ccd83f264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input6&quot;)</value>
      <webElementGuid>6f91e0c0-1f3c-48d0-9cf4-fbaf213fad47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input6']</value>
      <webElementGuid>ad02da10-e74d-435a-8dc8-5e965c8db3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qbf-verify-box']/form/div/div[3]/div[2]/input[2]</value>
      <webElementGuid>538b5493-6f8b-4f70-97e3-d54110a78123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input[2]</value>
      <webElementGuid>6c01a630-eb74-4a87-a155-20cdb0a9f711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'YY' and @id = 'input6']</value>
      <webElementGuid>43df574d-3918-47bf-9b79-077d2bd32e51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
