<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Min. Transaction Amount_MinTransactionAmount</name>
   <tag></tag>
   <elementGuidId>48a7fc62-1aac-4866-82bf-c4f8bd1645c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MinTransactionAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MinTransactionAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9369b9c-be27-495d-8966-f02689ea9ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qba-input small ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>5a967c65-475f-46ac-8edb-c9c92e787b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MinTransactionAmount</value>
      <webElementGuid>5632412c-a2dc-4a77-9eff-134cb7f6d8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>userCtrl.MinTransactionAmount</value>
      <webElementGuid>2d1ec187-c55c-4b7f-988e-28bc5e612ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>userCtrl.minBalanceFormat(userCtrl.MinTransactionAmount)</value>
      <webElementGuid>c3bfd981-a9d9-4e55-a333-c48a73851520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qba-gridBox&quot;)/div[@class=&quot;grid-item&quot;]/div[@class=&quot;qba-gridContains ng-scope&quot;]/input[@id=&quot;MinTransactionAmount&quot;]</value>
      <webElementGuid>497d1fee-add2-415b-a786-4f66068ad126</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MinTransactionAmount']</value>
      <webElementGuid>0c579865-b580-4474-948b-131af4b36b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='qba-gridBox']/div[5]/div/input</value>
      <webElementGuid>ccec5a07-84d5-4a55-9069-04b3f79ed189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>621c59f6-9451-4cac-95f0-6e6957e63333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MinTransactionAmount']</value>
      <webElementGuid>0b1ed01a-0003-4a96-b88c-dc04b1b590c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
