<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Credit Card Number_input2</name>
   <tag></tag>
   <elementGuidId>8b081932-a436-4872-95dc-0d332660a2bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52232c8d-65e4-4367-ae9c-611edcccce97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>userCtrl.cc_num2</value>
      <webElementGuid>656fdf2f-b537-4875-abfc-f9f9a8e1d8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-input xs ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength</value>
      <webElementGuid>6de7edfc-5763-450d-894b-cb3079e44da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>51b3086c-8726-4dbd-9791-14803d9d6698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1841fdaf-2007-496e-b5a5-cc1e821136d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input2</value>
      <webElementGuid>0447a158-370c-4c6c-a806-09f27b550f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto-tab-to</name>
      <type>Main</type>
      <value>input3</value>
      <webElementGuid>2df9da6a-74f1-4d94-bba5-9a846e7606ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input2&quot;)</value>
      <webElementGuid>87fa91b0-bcf5-4096-b09f-46a7253ecf1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input2']</value>
      <webElementGuid>166c4f2d-f2ca-4cc4-a038-766f8974468e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qbf-card-box']/div[2]/input[2]</value>
      <webElementGuid>8d4c0d14-e744-45fa-a10a-356289dc7b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>d9eed2eb-d8e1-47f0-9cab-205a55ce2f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input2']</value>
      <webElementGuid>f5079892-c0b0-4dc6-8588-2a366f016ee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
