<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input5</name>
   <tag></tag>
   <elementGuidId>ca63814d-a5cb-4568-ad22-42e9ab11cb23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28c25562-71fe-4417-a26e-aeb9a4756d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-input xs ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>d3fdaeaa-7d21-4aab-aa54-9e6d1feb1615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>08088bdf-bdcc-47e5-aa16-2a98440d645e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>userCtrl.newCC.month</value>
      <webElementGuid>c03ed000-cba7-4820-95c0-b5f5567528e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM</value>
      <webElementGuid>206d664a-0920-4e17-af27-eef6e083f750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input5</value>
      <webElementGuid>a3beb9ff-9fc7-425c-a0ed-0badb8a4bd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto-tab-to</name>
      <type>Main</type>
      <value>input6</value>
      <webElementGuid>e7865909-4937-4ce0-be22-682763a5f5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input5&quot;)</value>
      <webElementGuid>415baeea-a75d-48e2-bfde-d319d65352bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input5']</value>
      <webElementGuid>51232c0c-1ed5-47d7-abd6-4a75d2fac953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qbf-verify-box']/form/div/div[3]/div[2]/input</value>
      <webElementGuid>ef600ea4-e582-4a11-83ba-c43cab3adec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>92e80908-183c-411d-a4c9-1849d489d463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'MM' and @id = 'input5']</value>
      <webElementGuid>2076c994-6157-4995-b439-dc87ad37ba0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
