<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Transfer Amount_qbf-input small ng-un_ba31be</name>
   <tag></tag>
   <elementGuidId>0c6561fb-e542-4632-b4c5-2bc2cf268869</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.qbf-input.small.ng-untouched.ng-valid.ng-not-empty.ng-dirty.ng-valid-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b552a46a-ce2e-4de7-b10d-dc71401197b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-input small ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-number</value>
      <webElementGuid>0846373d-e0ed-44fb-8453-9fa817e2301f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>userCtrl.forms.billPayment.amount</value>
      <webElementGuid>2664ed58-88f2-4bf7-a96e-5dade61d3659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1f4dea9a-2f43-4d13-8c4b-541bf92af985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qbf-verify-box&quot;)/form[@class=&quot;ng-valid ng-scope ng-dirty ng-valid-number&quot;]/div[@class=&quot;row&quot;]/div[@id=&quot;qdf-fill-box&quot;]/div[@class=&quot;col-md-9&quot;]/input[@class=&quot;qbf-input small ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-number&quot;]</value>
      <webElementGuid>0f5ed152-7569-426d-85ac-6a00f8c187b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='number']</value>
      <webElementGuid>afaaf636-8db1-48c3-9f3f-03d2249ca4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='qdf-fill-box']/div[2]/input)[2]</value>
      <webElementGuid>2388ca2b-430f-42fc-a857-6c0a46b16270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>7b586219-c171-428d-8548-401fb9580ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>ffa2e4c6-b6a2-4169-b75c-772f3c6f3e1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
