<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--                Completed         _a8a910</name>
   <tag></tag>
   <elementGuidId>aa51ca67-03db-42bc-bddc-c67570ab782c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TransactionStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='TransactionStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b88512c9-511a-4ee2-ac3f-d22c178721bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qba-input small</value>
      <webElementGuid>459b5a57-0499-48bf-8175-f44c14a2ad9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TransactionStatus</value>
      <webElementGuid>12cc6a48-64f5-4c8c-b20b-16ede3dc4c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                --
                Completed
                Pending
                Reversed
                Failed
                Canceled
              </value>
      <webElementGuid>248d4039-ce51-426f-89fc-710971fc7f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TransactionStatus&quot;)</value>
      <webElementGuid>c4dcee0a-27b1-4baa-8ec6-7a83e3f5a566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TransactionStatus']</value>
      <webElementGuid>a66f5ad4-c1d9-4eaf-9f86-c5113ecc74db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='qba-gridBox']/div[2]/div/select</value>
      <webElementGuid>8bd254ae-8d4a-4732-a948-0bc6644ed840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Status'])[1]/following::select[1]</value>
      <webElementGuid>d9abc19d-930a-44e4-b303-11ab61d65166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Type'])[1]/following::select[2]</value>
      <webElementGuid>f7b8ba84-b45f-48ed-9ab5-072ba6285d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Dates Until'])[1]/preceding::select[1]</value>
      <webElementGuid>ff180062-f466-418b-8920-3f341f1da29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Account'])[1]/preceding::select[1]</value>
      <webElementGuid>d917c257-7513-4ff1-bdb5-529d66da3364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>afcf4670-7913-4ae3-b801-57e008579757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'TransactionStatus' and (text() = '
                --
                Completed
                Pending
                Reversed
                Failed
                Canceled
              ' or . = '
                --
                Completed
                Pending
                Reversed
                Failed
                Canceled
              ')]</value>
      <webElementGuid>1bb40428-4f98-4322-b790-ba300cf000e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
